# Notebook
https://www.kaggle.com/williamroe/bi-lstm-with-crf-for-ner

In [1]:
# %pip uninstall --yes tensorflow-cpu
# %pip uninstall --yes tensorflow
# %pip uninstall --yes tensorflow_addons
# %pip uninstall --yes keras-crf
# %pip uninstall --yes tf2crf
# %pip uninstall --yes keras-contrib  # Successfully uninstalled keras-contrib-2.0.8
# %pip uninstall --yes keras  # Successfully uninstalled Keras-2.2.1
# %pip uninstall --yes s3fs

Found existing installation: tensorflow-cpu 2.3.0
Uninstalling tensorflow-cpu-2.3.0:
  Successfully uninstalled tensorflow-cpu-2.3.0
Note: you may need to restart the kernel to use updated packages.
Found existing installation: tensorflow 2.3.0
Uninstalling tensorflow-2.3.0:
  Successfully uninstalled tensorflow-2.3.0
Note: you may need to restart the kernel to use updated packages.
Found existing installation: tensorflow-addons 0.13.0
Uninstalling tensorflow-addons-0.13.0:
  Successfully uninstalled tensorflow-addons-0.13.0
Note: you may need to restart the kernel to use updated packages.
Note: you may need to restart the kernel to use updated packages.
Note: you may need to restart the kernel to use updated packages.
Note: you may need to restart the kernel to use updated packages.
Found existing installation: Keras 2.1.6
Uninstalling Keras-2.1.6:
  Successfully uninstalled Keras-2.1.6
Note: you may need to restart the kernel to use updated packages.
Note: you may need to restart the

In [1]:
%pip install keras==2.1.6

  Using cached Keras-2.1.6-py2.py3-none-any.whl (339 kB)
Note: you may need to restart the kernel to use updated packages.


In [2]:
%pip install tensorflow-cpu==2.3.0

# keras-applications 1.0.4 requires keras>=2.1.6, which is not installed.

  Using cached tensorflow_cpu-2.3.0-cp38-cp38-macosx_10_11_x86_64.whl (165.2 MB)
Note: you may need to restart the kernel to use updated packages.


In [3]:
# %pip install tensorflow==2.4.0  # 2.5.0  # 2.2.0
%pip install tensorflow==2.3.0 

  Using cached tensorflow-2.3.0-cp38-cp38-macosx_10_11_x86_64.whl (165.2 MB)
Note: you may need to restart the kernel to use updated packages.


In [4]:
%pip install tensorflow_addons==0.13.0

  Using cached tensorflow_addons-0.13.0-cp38-cp38-macosx_10_13_x86_64.whl (511 kB)
Note: you may need to restart the kernel to use updated packages.


In [ ]:
# %pip install keras-crf==0.2.0

In [ ]:
# %pip install git+https://www.github.com/keras-team/keras-contrib.git
# # %pip install keras-contrib==0.1

In [119]:
# https://github.com/xuxingya/tf2crf
%pip install tf2crf==0.1.32

  Using cached tf2crf-0.1.32-py2.py3-none-any.whl (14 kB)
Note: you may need to restart the kernel to use updated packages.


In [ ]:
# %env SM_FRAMEWORK=tf.keras

In [ ]:
# %pip uninstall --yes tf-nightly

In [ ]:
# %pip install s3fs

In [2]:
import numpy as np
import pandas as pd 
# import s3fs

what_corpus = 'data_total'  # 'polnear', 'parc30'
what_type_files = 'train'
what_type_test_file = 'test'
what_type_val_file = 'dev'

# filepath = 's3://sagemaker-studio-528576943967-ssf9zkrg3os/polnear-conll/prepared/'
filepath = '../' + what_corpus + '-conll/prepared/'

In [3]:
train_filename = what_corpus + '_preprocessed_' + what_type_files + '_noBIO.csv'
df_train = pd.read_csv(filepath + train_filename, sep=";")

In [4]:
df_train[df_train['tag'].isna()]

Empty DataFrame
Columns: [Unnamed: 0, Unnamed: 0.1, filename, sentence_idx, word, tag]
Index: []

In [5]:
print(len(df_train.index))
del df_train['Unnamed: 0']
df_train.head(20)

1794014


Unnamed: 0.1                                           filename  \
0              0  politico_2016-05-22_mark-cuban-i-d-consider-a-...   
1              1  politico_2016-05-22_mark-cuban-i-d-consider-a-...   
2              2  politico_2016-05-22_mark-cuban-i-d-consider-a-...   
3              3  politico_2016-05-22_mark-cuban-i-d-consider-a-...   
4              4  politico_2016-05-22_mark-cuban-i-d-consider-a-...   
5              5  politico_2016-05-22_mark-cuban-i-d-consider-a-...   
6              6  politico_2016-05-22_mark-cuban-i-d-consider-a-...   
7              7  politico_2016-05-22_mark-cuban-i-d-consider-a-...   
8              8  politico_2016-05-22_mark-cuban-i-d-consider-a-...   
9              9  politico_2016-05-22_mark-cuban-i-d-consider-a-...   
10            10  politico_2016-05-22_mark-cuban-i-d-consider-a-...   
11            11  politico_2016-05-22_mark-cuban-i-d-consider-a-...   
12            12  politico_2016-05-22_mark-cuban-i-d-consider-a-...   
13            13  politico_2016-05-22_mark-cuban-i-d-consider-a-...   
14            14  politico_2016-05-22_mark-cuban-i-d-consider-a-...   
15            15  politico_2016-05-22_mark-cuban-i-d-consider-a-...   
16            16  politico_2016-05-22_mark-cuban-i-d-consider-a-...   
17            17  politico_2016-05-22_mark-cuban-i-d-consider-a-...   
18            18  politico_2016-05-22_mark-cuban-i-d-consider-a-...   
19            19  politico_2016-05-22_mark-cuban-i-d-consider-a-...   

    sentence_idx         word      tag  
0              1         Mark   SOURCE  
1              1        Cuban   SOURCE  
2              1            :      CUE  
3              1            I  CONTENT  
4              1        would  CONTENT  
5              1     consider  CONTENT  
6              1            a  CONTENT  
7              1       future  CONTENT  
8              1        White  CONTENT  
9              1        House  CONTENT  
10             1          bid  CONTENT  
11             1            .        O  
12             2         Mark   SOURCE  
13             2        Cuban   SOURCE  
14             2            ,   SOURCE  
15             2          the   SOURCE  
16             2  billionaire   SOURCE  
17             2        owner   SOURCE  
18             2           of   SOURCE  
19             2          the   SOURCE

In [6]:
test_filename = what_corpus + '_preprocessed_' + what_type_test_file + '_noBIO.csv'
df_test = pd.read_csv(filepath + test_filename, sep=";")

In [7]:
print(len(df_test.index))
del df_test['Unnamed: 0']
df_test.head(20)

130042


Unnamed: 0.1                                           filename  \
0              0  huff-post_2016-11-05_hillary-clinton-drops-int...   
1              1  huff-post_2016-11-05_hillary-clinton-drops-int...   
2              2  huff-post_2016-11-05_hillary-clinton-drops-int...   
3              3  huff-post_2016-11-05_hillary-clinton-drops-int...   
4              4  huff-post_2016-11-05_hillary-clinton-drops-int...   
5              5  huff-post_2016-11-05_hillary-clinton-drops-int...   
6              6  huff-post_2016-11-05_hillary-clinton-drops-int...   
7              7  huff-post_2016-11-05_hillary-clinton-drops-int...   
8              8  huff-post_2016-11-05_hillary-clinton-drops-int...   
9              9  huff-post_2016-11-05_hillary-clinton-drops-int...   
10            10  huff-post_2016-11-05_hillary-clinton-drops-int...   
11            11  huff-post_2016-11-05_hillary-clinton-drops-int...   
12            12  huff-post_2016-11-05_hillary-clinton-drops-int...   
13            13  huff-post_2016-11-05_hillary-clinton-drops-int...   
14            14  huff-post_2016-11-05_hillary-clinton-drops-int...   
15            15  huff-post_2016-11-05_hillary-clinton-drops-int...   
16            16  huff-post_2016-11-05_hillary-clinton-drops-int...   
17            17  huff-post_2016-11-05_hillary-clinton-drops-int...   
18            18  huff-post_2016-11-05_hillary-clinton-drops-int...   
19            19  huff-post_2016-11-05_hillary-clinton-drops-int...   

    sentence_idx          word      tag  
0              1       Hillary        O  
1              1       Clinton        O  
2              1         drops        O  
3              1          Into        O  
4              1       Detroit        O  
5              1            as        O  
6              1     Democrats   SOURCE  
7              1           get      CUE  
8              1       nervous      CUE  
9              1         about      CUE  
10             1         black  CONTENT  
11             1       turnout  CONTENT  
12             1             .        O  
13             2       DETROIT        O  
14             2            --        O  
15             2          with        O  
16             2     Democrats   SOURCE  
17             2  increasingly      CUE  
18             2       nervous      CUE  
19             2         about      CUE

In [8]:
df_test[df_test['tag'].isna()]

Empty DataFrame
Columns: [Unnamed: 0.1, filename, sentence_idx, word, tag]
Index: []

In [9]:
val_filename = what_corpus + '_preprocessed_' + what_type_val_file + '_noBIO.csv'
df_val = pd.read_csv(filepath + val_filename, sep=";")

In [10]:
print(len(df_val.index))
del df_val['Unnamed: 0']
df_val.head(20)

111200


Unnamed: 0.1                                           filename  \
0              0  west-journal_2016-09-29_gold-star-mom-corners-...   
1              1  west-journal_2016-09-29_gold-star-mom-corners-...   
2              2  west-journal_2016-09-29_gold-star-mom-corners-...   
3              3  west-journal_2016-09-29_gold-star-mom-corners-...   
4              4  west-journal_2016-09-29_gold-star-mom-corners-...   
5              5  west-journal_2016-09-29_gold-star-mom-corners-...   
6              6  west-journal_2016-09-29_gold-star-mom-corners-...   
7              7  west-journal_2016-09-29_gold-star-mom-corners-...   
8              8  west-journal_2016-09-29_gold-star-mom-corners-...   
9              9  west-journal_2016-09-29_gold-star-mom-corners-...   
10            10  west-journal_2016-09-29_gold-star-mom-corners-...   
11            11  west-journal_2016-09-29_gold-star-mom-corners-...   
12            12  west-journal_2016-09-29_gold-star-mom-corners-...   
13            13  west-journal_2016-09-29_gold-star-mom-corners-...   
14            14  west-journal_2016-09-29_gold-star-mom-corners-...   
15            15  west-journal_2016-09-29_gold-star-mom-corners-...   
16            16  west-journal_2016-09-29_gold-star-mom-corners-...   
17            17  west-journal_2016-09-29_gold-star-mom-corners-...   
18            18  west-journal_2016-09-29_gold-star-mom-corners-...   
19            19  west-journal_2016-09-29_gold-star-mom-corners-...   

    sentence_idx       word      tag  
0              1       Gold        O  
1              1       Star        O  
2              1        mom        O  
3              1    Corners        O  
4              1      Obama        O  
5              1         on        O  
6              1         he   SOURCE  
7              1    refusal      CUE  
8              1         to  CONTENT  
9              1        use  CONTENT  
10             1        the  CONTENT  
11             1       word  CONTENT  
12             1          `  CONTENT  
13             1    islamic  CONTENT  
14             1  terrorist  CONTENT  
15             1          .  CONTENT  
16             1          '  CONTENT  
17             2  President   SOURCE  
18             2     Barack   SOURCE  
19             2      Obama   SOURCE

In [11]:
df_val[df_val['tag'].isna()]

Empty DataFrame
Columns: [Unnamed: 0.1, filename, sentence_idx, word, tag]
Index: []

In [12]:
class SentenceGetter(object):
    
    def __init__(self, dataset):
        self.n_sent = 1
        self.dataset = dataset
        self.empty = False
#         agg_func = lambda s: ' '.join(s["word"].values.tolist())
        agg_func = lambda s: [(w, t) for w,t in zip(s["word"].values.tolist(),
                                                        s["tag"].values.tolist())]
        self.grouped = self.dataset.groupby(["filename", "sentence_idx"]).apply(agg_func)
#         self.grouped = self.dataset.groupby(["sentence_idx"]).apply(agg_func)
        self.sentences = [s for s in self.grouped]
    
    def get_next(self):
        try:
            s = self.grouped["Sentence: {}".format(self.n_sent)]
            self.n_sent += 1
            return s
        except:
            return None

In [13]:
getter_train = SentenceGetter(df_train)
getter_test = SentenceGetter(df_test)
getter_val = SentenceGetter(df_val)

In [14]:
sentences_train = getter_train.sentences
sentences_test = getter_test.sentences
sentences_val = getter_val.sentences

In [15]:
print(len(sentences_train))
# sentences_train[0:10]

75048


In [16]:
sentences_train_only_labeled = []
for sentence_train in sentences_train:
    is_labeled = False
    for sentence_train_word in sentence_train:
        label = sentence_train_word[1] # Label is the second of the tuple
        if label != 'O':
            is_labeled = True
            break
    if is_labeled:
        sentences_train_only_labeled.append(sentence_train)
        
sentences_train = sentences_train_only_labeled
print(len(sentences_train))
print(len(sentences_train)/2)
sentences_train[0:2]

38179
19089.5


[[('in', 'O'),
  ('we', 'O'),
  ('last', 'O'),
  ('epistle', 'O'),
  ('from', 'O'),
  ('the', 'O'),
  ('bottomless', 'O'),
  ('pit', 'O'),
  (',', 'O'),
  ('we', 'SOURCE'),
  ('mock', 'CUE'),
  ('the', 'CONTENT'),
  ('presidential', 'CONTENT'),
  ('ambition', 'CONTENT'),
  ('of', 'CONTENT'),
  ('three', 'CONTENT'),
  ('republican', 'CONTENT'),
  ('hopeful', 'CONTENT'),
  (':', 'CONTENT'),
  ('Jeb', 'CONTENT'),
  ('!', 'CONTENT')],
 [(',', 'CONTENT'),
  ('Ben', 'CONTENT'),
  ('Carson', 'CONTENT'),
  (',', 'CONTENT'),
  ('and', 'CONTENT'),
  ('Donald', 'CONTENT'),
  ('Trump', 'CONTENT'),
  ('.', 'O')]]

In [17]:
# sentences_train = sentences_train[0:15171]  # parc: 22352]
# print(len(sentences_train))

In [18]:
print(sentences_train[1])

[(',', 'CONTENT'), ('Ben', 'CONTENT'), ('Carson', 'CONTENT'), (',', 'CONTENT'), ('and', 'CONTENT'), ('Donald', 'CONTENT'), ('Trump', 'CONTENT'), ('.', 'O')]


In [19]:
# print(sentences_train[10])

In [20]:
print(len(sentences_test))

5438


In [21]:
# print(sentences_test[10])

In [22]:
maxlen = max([len(s) for s in sentences_train])
print ('Maximum sequence length train:', maxlen)
maxlen_test = max([len(s) for s in sentences_test])
print ('Maximum sequence length test:', maxlen_test)
maxlen_val = max([len(s) for s in sentences_val])
print ('Maximum sequence length val:', maxlen_val)

Maximum sequence length train: 141
Maximum sequence length test: 94
Maximum sequence length val: 116


In [23]:
# words_train = ['', '[UNK]']
# words_train.extend(list(set(df_train["word"].values)))
# words_train.append("ENDPAD")
# words_train[0:5]

In [24]:
sentences_texts_train = [' '.join([w[0] for w in s]) for s in sentences_train]
sentences_texts_train[1]

', Ben Carson , and Donald Trump .'

In [25]:
sentences_texts_test = [' '.join([w[0] for w in s]) for s in sentences_test]
sentences_texts_test[1]

'Washington -lrb- AFP -rrb- -- the Washington Post on Thursday become the latest US newspaper to emphatically endorse Hillary Clinton for the White House , say it be sway as much by she competence as by the alarming specter of a Donald Trump presidency .'

In [26]:
sentences_texts_val = [' '.join([w[0] for w in s]) for s in sentences_val]
sentences_texts_val[1]

"the New York Post report that Hillary Clinton 's team avoid take she to the emergency room follow she medical scare on Sunday in order to `` keep the detail of she medical treatment under wrap . ''"

https://keras.io/examples/nlp/pretrained_word_embeddings/

https://towardsdatascience.com/simple-bert-using-tensorflow-2-0-132cb19e9b22


In [27]:
from tensorflow.data import Dataset
from tensorflow.keras.layers.experimental.preprocessing import TextVectorization

vectorizer = TextVectorization(max_tokens=50000, output_sequence_length=maxlen)
# vectorizer = TextVectorization(max_tokens=20000, output_sequence_length=200)
# text_ds = Dataset.from_tensor_slices(df_train["word"].values).batch(128)
text_ds = Dataset.from_tensor_slices(sentences_texts_train).batch(128)
vectorizer.adapt(text_ds)

In [28]:
vectorizer.get_vocabulary()[:5]

['', '[UNK]', 'the', 'be', 'to']

In [29]:
# output = vectorizer([["the cat sat on the mat"]])
# output.numpy()[0, :6]

In [30]:
voc = vectorizer.get_vocabulary()
word_index = dict(zip(voc, range(len(voc))))

In [31]:
test = ["the", "be", "get", "on", "the"]
[word_index[w] for w in test]

[2, 3, 65, 17, 2]

In [32]:
from gensim.models import KeyedVectors
# word_vecs = KeyedVectors.load_word2vec_format("glove.txt") 
# https://www.kaggle.com/watts2/glove6b50dtxt
glove_dimensions = 50
!python -m gensim.scripts.glove2word2vec --input  glove.6B.50d.txt --output glove.6B.50d.w2vformat.txt
word_vecs = KeyedVectors.load_word2vec_format("glove.6B.50d.w2vformat.txt")

/Users/bettyvandongen/opt/anaconda3/lib/python3.8/runpy.py:127: RuntimeWarning: 'gensim.scripts.glove2word2vec' found in sys.modules after import of package 'gensim.scripts', but prior to execution of 'gensim.scripts.glove2word2vec'; this may result in unpredictable behaviour
  warn(RuntimeWarning(msg))
2021-06-17 10:26:53,691 - glove2word2vec - INFO - running /Users/bettyvandongen/opt/anaconda3/lib/python3.8/site-packages/gensim/scripts/glove2word2vec.py --input glove.6B.50d.txt --output glove.6B.50d.w2vformat.txt
2021-06-17 10:26:53,824 - glove2word2vec - INFO - converting 400000 vectors from glove.6B.50d.txt to glove.6B.50d.w2vformat.txt
2021-06-17 10:26:54,531 - glove2word2vec - INFO - Converted model with 400000 vectors and 50 dimensions


In [33]:
# Test word_vecs
word_vecs.word_vec('the')

array([ 4.1800e-01,  2.4968e-01, -4.1242e-01,  1.2170e-01,  3.4527e-01,
       -4.4457e-02, -4.9688e-01, -1.7862e-01, -6.6023e-04, -6.5660e-01,
        2.7843e-01, -1.4767e-01, -5.5677e-01,  1.4658e-01, -9.5095e-03,
        1.1658e-02,  1.0204e-01, -1.2792e-01, -8.4430e-01, -1.2181e-01,
       -1.6801e-02, -3.3279e-01, -1.5520e-01, -2.3131e-01, -1.9181e-01,
       -1.8823e+00, -7.6746e-01,  9.9051e-02, -4.2125e-01, -1.9526e-01,
        4.0071e+00, -1.8594e-01, -5.2287e-01, -3.1681e-01,  5.9213e-04,
        7.4449e-03,  1.7778e-01, -1.5897e-01,  1.2041e-02, -5.4223e-02,
       -2.9871e-01, -1.5749e-01, -3.4758e-01, -4.5637e-02, -4.4251e-01,
        1.8785e-01,  2.7849e-03, -1.8411e-01, -1.1514e-01, -7.8581e-01],
      dtype=float32)

In [34]:
# np.array(word_vecs.word_vec('the')).astype(np.float16)

In [35]:
num_tokens = len(voc) + 2
embedding_dim = glove_dimensions
hits = 0
misses = 0

# Prepare embedding matrix
embedding_matrix = np.zeros((num_tokens, embedding_dim))
for word, i in word_index.items():
# for i, word in enumerate(words_train):
#     embedding_vector = embeddings_index.get(word)
#     print(i)
    try:
        embedding_vector = word_vecs.word_vec(word)
#     if embedding_vector is not None:
        # Words not found in embedding index will be all-zeros.
        # This includes the representation for "padding" and "OOV"
        embedding_matrix[i] = embedding_vector
        hits += 1
#     else:
    except KeyError:
        misses += 1
print("Converted %d words (%d misses)" % (hits, misses))

Converted 23504 words (5667 misses)


In [36]:
# words_test = list(set(df_test["word"].values))
# words_test.append("ENDPAD")

In [37]:
# n_words = len(words_train)
# n_words

In [38]:
# df_train[df_train['tag'].isna()]

In [39]:
from math import nan

tags = []
for index, tag in enumerate(set(df_train["tag"].values)):
    if tag is nan or isinstance(tag, float):
        tags.append('unk')
    else:
        tags.append(tag)
print(tags)

['O', 'CONTENT', 'SOURCE', 'CUE']


In [40]:
n_tags = len(tags); n_tags

4

In [41]:
from future.utils import iteritems
# word2idx_train = {w: i for i, w in enumerate(words_train)}
# word2idx_test = {w: i for i, w in enumerate(words_test)}

tag2idx = {t: i for i, t in enumerate(tags)}
idx2tag = {v: k for k, v in iteritems(tag2idx)}

In [42]:
# word2idx_train['the']

In [43]:
# word2idx

In [44]:
tag2idx["O"]

0

In [45]:
print(tag2idx)

{'O': 0, 'CONTENT': 1, 'SOURCE': 2, 'CUE': 3}


In [46]:
idx2tag[3]

'CUE'

In [47]:
idx2tag

{0: 'O', 1: 'CONTENT', 2: 'SOURCE', 3: 'CUE'}

In [48]:
X_train = vectorizer(np.array([[s] for s in sentences_texts_train])).numpy()
X_test = vectorizer(np.array([[s] for s in sentences_texts_test])).numpy()
X_val = vectorizer(np.array([[s] for s in sentences_texts_val])).numpy()

In [49]:
from tensorflow.keras.preprocessing.sequence import pad_sequences

In [50]:
# X_train = [[word2idx_train[w[0]] for w in s] for s in sentences_train]
# X_test = [[word2idx_test[w[0]] for w in s] for s in sentences_test]

In [51]:
print(X_train[10])

[   2 1530  268  844  662   30    2  862    4 6428   18  166    0    0
    0    0    0    0    0    0    0    0    0    0    0    0    0    0
    0    0    0    0    0    0    0    0    0    0    0    0    0    0
    0    0    0    0    0    0    0    0    0    0    0    0    0    0
    0    0    0    0    0    0    0    0    0    0    0    0    0    0
    0    0    0    0    0    0    0    0    0    0    0    0    0    0
    0    0    0    0    0    0    0    0    0    0    0    0    0    0
    0    0    0    0    0    0    0    0    0    0    0    0    0    0
    0    0    0    0    0    0    0    0    0    0    0    0    0    0
    0    0    0    0    0    0    0    0    0    0    0    0    0    0
    0]


In [52]:
np.array(X_train).shape

(38179, 141)

In [53]:
# X_train = pad_sequences(maxlen=maxlen, sequences=X_train, padding="post",value=n_words - 1)
# print(X_train[10])

In [54]:
# X_test = pad_sequences(maxlen=maxlen, sequences=X_test, padding="post",value=n_words - 1)
# print(X_test[10])

In [55]:
y_idx_train = [[tag2idx[w[1]] for w in s] for s in sentences_train]
# print('sentences_train[25]')
# print(sentences_train[25])
# print('y_idx_train[25]')
# print(y_idx_train[25])
# print('sentences_train[10]')
# print(sentences_train[10])
# print('y_idx_train[10]')
# print(y_idx_train[10])
# print(len(y_idx_train[10]))

In [56]:
y_idx_test = [[tag2idx[w[1]] for w in s] for s in sentences_test]
# print('sentences_test[25]')
# print(sentences_test[25])
# print('y_idx_test[25]')
# print(y_idx_test[25])
# print('sentences_test[10]')
# print(sentences_test[10])
# print('y_idx_test[10]')
# print(y_idx_test[10])
# print(len(y_idx_test[10]))

In [57]:
y_idx_val = [[tag2idx[w[1]] for w in s] for s in sentences_val]

In [58]:
y_train = pad_sequences(maxlen=maxlen, sequences=y_idx_train, padding="post", value=tag2idx["O"])
print(y_train[10])
print(len(y_train[10]))

[1 1 1 1 1 1 1 1 1 1 1 1 1 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
141


In [59]:
y_test = pad_sequences(maxlen=maxlen, sequences=y_idx_test, padding="post", value=tag2idx["O"])
print(y_test[10])
print(len(y_test[10]))

[2 2 2 3 3 3 3 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
141


In [60]:
y_val = pad_sequences(maxlen=maxlen, sequences=y_idx_val, padding="post", value=tag2idx["O"])
print(y_val[10])
print(len(y_val[10]))

[1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 3 2 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
141


In [61]:
from tensorflow.keras.utils import to_categorical
y_train = [to_categorical(i, num_classes=n_tags) for i in y_train]
print(y_train[10][0])

[0. 1. 0. 0.]


In [62]:
y_test = [to_categorical(i, num_classes=n_tags) for i in y_test]
print(y_test[10][0])

[0. 0. 1. 0.]


In [63]:
y_val = [to_categorical(i, num_classes=n_tags) for i in y_val]
print(y_val[10][0])

[0. 1. 0. 0.]


In [64]:
# from sklearn.model_selection import train_test_split
# X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.5)

# X_train, y_train = X, y
# X_test, y_test = X, y

In [65]:
print(X_train[10][0])
print(X_test[10][0])
print(X_val[10][0])
print(y_train[10][0])
print(y_test[10][0])
print(y_val[10][0])

2
2
47
[0. 1. 0. 0.]
[0. 0. 1. 0.]
[0. 1. 0. 0.]


In [66]:
from tensorflow.keras.initializers import Constant
from tensorflow.keras.layers import Input, InputLayer, LSTM, Embedding, Dense, TimeDistributed, Dropout, Bidirectional
from tensorflow.keras.models import Model, Sequential  # , Input
import tensorflow.keras as k
import tensorflow as tf

In [67]:
print(k.__version__)

2.4.0


In [68]:
print(tf.version.VERSION)

2.3.0


In [69]:
# import tensorflow.keras.utils as generic_utils
# from keras_contrib.layers.crf import CRF
# AttributeError: module 'tensorflow.compat.v2' has no attribute '__internal__'

In [70]:
word_embedding_size = embedding_dim  # glove_dimensions

https://github.com/xuxingya/tf2crf

More inspiration:
https://github.com/Akshayc1/named-entity-recognition/blob/master/NER%20using%20Bidirectional%20LSTM%20-%20CRF%20.ipynb

https://www.kaggle.com/nikkisharma536/ner-with-bilstm-and-crf

In [71]:
# # Kaggle example code 

# inputs = Input(shape=(None,), dtype="int64")  
# # inputs = Input(shape=(maxlen,))
# # https://stackoverflow.com/questions/55770009/how-to-use-a-pre-trained-embedding-matrix-in-tensorflow-2-0-rnn-as-initial-weigh
# # https://keras.io/examples/nlp/pretrained_word_embeddings/ --> pretrained embeddings
# # outputs = Embedding(input_dim=n_words, output_dim=word_embedding_size, input_length=maxlen)(inputs)
# outputs = Embedding(num_tokens, embedding_dim, embeddings_initializer=Constant(embedding_matrix), trainable=False,)(inputs)
# outputs = Bidirectional(LSTM(units=word_embedding_size, 
#                              return_sequences=True, 
#                              dropout=0.5,  # 0.2, 0.5, 
#                              recurrent_dropout=0.5,  # 0.2, 0.5, 
#                              kernel_initializer=k.initializers.he_normal()))(outputs)
# # https://github.com/xuxingya/tf2crf: Add internal kernel like CRF in keras_contrib, so now there is no need to stack a Dense layer before the CRF layer.
# outputs = TimeDistributed(Dense(n_tags, activation="relu"))(outputs)  # previously softmax output layer
# # outputs = TimeDistributed(Dense(n_tags, activation=tensorflow.keras.activations.softmax))(outputs)  # previously softmax output layer

# # crf = CRF(n_tags)  # CRF layer
# # outputs = crf(outputs)  # output

# model = Model(inputs, outputs)

# # adam = k.optimizers.Adam(lr=0.0005, beta_1=0.9, beta_2=0.999)
# adam = k.optimizers.Adam(learning_rate=0.0005, beta_1=0.9, beta_2=0.999)

# # https://stackoverflow.com/questions/61742556/valueerror-shapes-none-1-and-none-2-are-incompatible
# # model.compile(optimizer='adam', loss="sparse_categorical_crossentropy", metrics=["accuracy"])
# model.compile(optimizer=adam, loss="categorical_crossentropy", metrics=["accuracy"])  # categorical_accuracy?
# # model.compile(loss="sparse_categorical_crossentropy", optimizer="rmsprop", metrics=["acc"])
# # model.compile(optimizer=adam, loss=crf.loss_function, metrics=[crf.accuracy, 'accuracy'])# Saving the best only

# model.summary()

In [78]:
# # tfcrf version
# from tf2crf import CRF
# from tf2crf import ModelWithCRFLoss

# inputs = Input(shape=(None,), dtype="int64")  
# # inputs = Input(shape=(maxlen,))
# # https://stackoverflow.com/questions/55770009/how-to-use-a-pre-trained-embedding-matrix-in-tensorflow-2-0-rnn-as-initial-weigh
# # https://keras.io/examples/nlp/pretrained_word_embeddings/ --> pretrained embeddings
# # outputs = Embedding(input_dim=n_words, output_dim=word_embedding_size, input_length=maxlen)(inputs)
# outputs = Embedding(num_tokens, embedding_dim, embeddings_initializer=Constant(embedding_matrix), trainable=False,)(inputs)
# outputs = Bidirectional(LSTM(units=word_embedding_size, 
#                              return_sequences=True, 
#                              dropout=0.5,  # 0.2, 0.5, 
#                              recurrent_dropout=0.5,  # 0.2, 0.5, 
#                              kernel_initializer=k.initializers.he_normal()))(outputs)
# # https://github.com/xuxingya/tf2crf: Add internal kernel like CRF in keras_contrib, so now there is no need to stack a Dense layer before the CRF layer.
# # outputs = TimeDistributed(Dense(n_tags, activation="relu"))(outputs)  # previously softmax output layer
# # outputs = TimeDistributed(Dense(n_tags, activation=tensorflow.keras.activations.softmax))(outputs)  # previously softmax output layer

# crf = CRF(n_tags)  # CRF layer
# outputs = crf(outputs)  # output

# # adam = k.optimizers.Adam(lr=0.0005, beta_1=0.9, beta_2=0.999)
# adam = k.optimizers.Adam(learning_rate=0.0005, beta_1=0.9, beta_2=0.999)

# base_model = Model(inputs, outputs)
# model = ModelWithCRFLoss(base_model, sparse_target=False)  # True)

# model.compile(optimizer='adam')
# # model.compile(optimizer=adam)
# # https://stackoverflow.com/questions/61742556/valueerror-shapes-none-1-and-none-2-are-incompatible
# # model.compile(optimizer='adam', loss="sparse_categorical_crossentropy", metrics=["accuracy"])
# # model.compile(optimizer=adam, loss="categorical_crossentropy", metrics=["accuracy"])  # categorical_accuracy?
# # model.compile(loss="sparse_categorical_crossentropy", optimizer="rmsprop", metrics=["acc"])
# # model.compile(optimizer=adam, loss=crf.loss_function, metrics=[crf.accuracy, 'accuracy'])  # Saving the best only

In [81]:
# Sequential TF addons CRF
# https://github.com/tensorflow/addons/issues/1769
from crf import CRF

model = Sequential()
model.add(InputLayer(input_shape=(None,), dtype="int64"))
model.add(Embedding(num_tokens, embedding_dim, embeddings_initializer=Constant(embedding_matrix), trainable=False,))
model.add(Bidirectional(LSTM(units=word_embedding_size, 
                             return_sequences=True, 
                             dropout=0.5,  # 0.2, 0.5, 
                             recurrent_dropout=0.5,  # 0.2, 0.5, 
                             kernel_initializer=k.initializers.he_normal())))
model.add(TimeDistributed(Dense(n_tags, activation="relu")))

adam = k.optimizers.Adam(learning_rate=0.0005, beta_1=0.9, beta_2=0.999)

crf = CRF(n_tags, sparse_target=False)
model.add(crf)
model.compile(optimizer=adam, loss="categorical_crossentropy", metrics=["accuracy"])  # categorical_accuracy?
# model.compile(optimizer=adam, loss=crf.loss, metrics=[crf.accuracy])
model.summary()

# /Users/bettyvandongen/opt/anaconda3/lib/python3.8/site-packages/tensorflow_addons/text/crf.py:540: 
# UserWarning: CRF Decoding does not work with KerasTensors in TF2.4. The bug has since been fixed in tensorflow/tensorflow##45534

# /Users/bettyvandongen/opt/anaconda3/lib/python3.8/site-packages/tensorflow/python/autograph/impl/api.py:376: 
# UserWarning: CRF decoding models have serialization issues in TF >=2.5 . Please see isse #2476 return py_builtins.overload_of(f)(*args)

Model: "sequential"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
embedding_2 (Embedding)      (None, None, 50)          1458650   
_________________________________________________________________
bidirectional_2 (Bidirection (None, None, 100)         40400     
_________________________________________________________________
time_distributed (TimeDistri (None, None, 4)           404       
_________________________________________________________________
crf_1 (CRF)                  (None, None, 4)           16        
Total params: 1,499,470
Trainable params: 40,820
Non-trainable params: 1,458,650
_________________________________________________________________


In [82]:
# # Model TF addons CRF
# # https://github.com/tensorflow/addons/issues/1769
# from crf import CRF

# inputs = Input(shape=(None,), dtype="int64")  
# # inputs = Input(shape=(maxlen,))
# # https://stackoverflow.com/questions/55770009/how-to-use-a-pre-trained-embedding-matrix-in-tensorflow-2-0-rnn-as-initial-weigh
# # https://keras.io/examples/nlp/pretrained_word_embeddings/ --> pretrained embeddings
# # outputs = Embedding(input_dim=n_words, output_dim=word_embedding_size, input_length=maxlen)(inputs)
# outputs = Embedding(num_tokens, embedding_dim, embeddings_initializer=Constant(embedding_matrix), trainable=False,)(inputs)
# outputs = Bidirectional(LSTM(units=word_embedding_size, 
#                              return_sequences=True, 
#                              dropout=0.5,  # 0.2, 0.5, 
#                              recurrent_dropout=0.5,  # 0.2, 0.5, 
#                              kernel_initializer=k.initializers.he_normal()))(outputs)
# # https://github.com/xuxingya/tf2crf: Add internal kernel like CRF in keras_contrib, so now there is no need to stack a Dense layer before the CRF layer.
# outputs = TimeDistributed(Dense(n_tags, activation="relu"))(outputs)  # previously softmax output layer
# # outputs = TimeDistributed(Dense(n_tags, activation=tensorflow.keras.activations.softmax))(outputs)  # previously softmax output layer

# crf = CRF(n_tags, sparse_target=False)
# outputs = crf(outputs)  # output
# model = Model(inputs, outputs)

# # adam = k.optimizers.Adam(lr=0.0005, beta_1=0.9, beta_2=0.999)
# adam = k.optimizers.Adam(learning_rate=0.0005, beta_1=0.9, beta_2=0.999)

# model = Model(inputs, outputs)

# # https://stackoverflow.com/questions/61742556/valueerror-shapes-none-1-and-none-2-are-incompatible
# # model.compile(optimizer='adam', loss="sparse_categorical_crossentropy", metrics=["accuracy"])
# model.compile(optimizer=adam, loss="categorical_crossentropy", metrics=["accuracy"])  # metrics=["categorical_accuracy"]?
# # model.compile(loss="sparse_categorical_crossentropy", optimizer="rmsprop", metrics=["acc"])
# # model.compile(optimizer=adam, loss=crf.loss_function, metrics=[crf.accuracy, 'accuracy'])# Saving the best only

# model.summary()

In [83]:
# # Saving the best only
from tensorflow.keras.callbacks import ModelCheckpoint

# filepath="ner-bi-lstm-td-model-{val_accuracy:.2f}.hdf5"
filepath = 'tmp/checkpoint'
checkpoint_acc = ModelCheckpoint(filepath + '/acc', monitor='val_accuracy', verbose=1, save_best_only=True, mode='max')
checkpoint_loss = ModelCheckpoint(filepath + '/loss', monitor='val_loss', verbose=1, save_best_only=True, mode='max')
callbacks_list = [checkpoint_acc, checkpoint_loss]

In [84]:
# # Generate generalization metrics
# i = len(X_test) - 1 
# score = model.evaluate(np.array([X_test[:i]]), y_test, verbose=0)
# print(f'Test loss: {score[0]} / Test accuracy: {score[1]}')

In [85]:
# model.fit(X_train, np.array(y_train), batch_size=256, epochs=1, validation_split=0.1, verbose=1, callbacks=callbacks_list)
model.fit(X_train, np.array(y_train), batch_size=256, epochs=2, validation_split=0.2, verbose=1, callbacks=callbacks_list)
# model.fit(X_train, np.array(y_train), batch_size=256, epochs=50, validation_data=(X_val, y_val), verbose=1, callbacks=callbacks_list)

Epoch 1/2
120/120 [==============================] - ETA: 0s - loss: nan - accuracy: 0.8490
Epoch 00001: val_accuracy improved from -inf to 0.84141, saving model to tmp/checkpoint/acc
Instructions for updating:
This property should not be used in TensorFlow 2.0, as updates are applied automatically.
Instructions for updating:
This property should not be used in TensorFlow 2.0, as updates are applied automatically.
INFO:tensorflow:Assets written to: tmp/checkpoint/acc/assets

Epoch 00001: val_loss improved from -inf to 2.55624, saving model to tmp/checkpoint/loss
INFO:tensorflow:Assets written to: tmp/checkpoint/loss/assets
120/120 [==============================] - 67s 556ms/step - loss: nan - accuracy: 0.8490 - val_loss: 2.5562 - val_accuracy: 0.8414
Epoch 2/2
120/120 [==============================] - ETA: 0s - loss: nan - accuracy: 0.8508
Epoch 00002: val_accuracy did not improve from 0.84141

Epoch 00002: val_loss did not improve from 2.55624
120/120 [==============================

In [86]:
# model.summary()

In [87]:
TP = {}
TN = {}
FP = {}
FN = {}
for tag in tag2idx.keys():
    TP[tag] = 0
    TN[tag] = 0    
    FP[tag] = 0    
    FN[tag] = 0    

def accumulate_score_by_tag(gt, pred):
    """
    For each tag keep stats
    """
    if gt == pred:
        TP[gt] += 1
    elif gt != 'O' and pred == 'O':
        FN[gt] +=1
    elif gt == 'O' and pred != 'O':
        FP[gt] += 1
    else:
        TN[gt] += 1

In [88]:
print(X_test)

[[  291   306   137 ...     0     0     0]
 [  291    96  5136 ...     0     0     0]
 [  115    32    12 ...     0     0     0]
 ...
 [14941 14160     9 ...     0     0     0]
 [    2     1   214 ...     0     0     0]
 [   56     3    76 ...     0     0     0]]


In [89]:
### Predict single sentence

In [90]:
# i = 2  # len(X_test) - 1  # Last one 
# p = model.predict(np.array([X_test[i]]))
# p = np.argmax(p, axis=-1)
# print(p.shape)
# gt = np.argmax(y_test[i], axis=-1)
# print(gt)
# print("{:14}: ({:5}): {}".format("Word", "True", "Pred"))
# print(p)
# for idx, (w,pred) in enumerate(zip(X_test[i],p[0])):
#     if words_test[w] == 'ENDPAD':
#         break
#     print("{:14}: ({:5}): {}".format(words_test[w],idx2tag[gt[idx]],tags[pred]))

In [91]:
p = model.predict(np.array(X_test))

In [92]:
p.shape

(5438, 141, 4)

In [93]:
p[0][0]

array([1., 0., 0., 0.], dtype=float32)

In [94]:
p[100][100]

array([1., 0., 0., 0.], dtype=float32)

In [95]:
# p

In [96]:
from sklearn.metrics import classification_report

In [97]:
axis = 2

In [98]:
np.argmax(p, axis=axis)[0]

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0])

In [99]:
print(classification_report(np.argmax(y_test, axis=axis).ravel(), np.argmax(p, axis=axis).ravel(),labels=list(idx2tag.keys()), target_names=list(idx2tag.values())))

# Warning might be caused by small test set compared to train set?
# /Users/bettyvandongen/opt/anaconda3/lib/python3.8/site-packages/sklearn/metrics/_classification.py:1221: UndefinedMetricWarning: 
# Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
#   _warn_prf(average, modifier, msg_start, len(result))

/Users/bettyvandongen/opt/anaconda3/lib/python3.8/site-packages/sklearn/metrics/_classification.py:1221: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


              precision    recall  f1-score   support

           O       0.91      1.00      0.95    696169
     CONTENT       0.00      0.00      0.00     56040
      SOURCE       0.00      0.00      0.00      9511
         CUE       0.00      0.00      0.00      5038

    accuracy                           0.91    766758
   macro avg       0.23      0.25      0.24    766758
weighted avg       0.82      0.91      0.86    766758



In [100]:
for i, sentence in enumerate(X_test):
    y_hat = np.argmax(p[i], axis=-1)
    gt = np.argmax(y_test[i], axis=-1)
    for idx, (w,pred) in enumerate(zip(sentence,y_hat)):
        accumulate_score_by_tag(idx2tag[gt[idx]],tags[pred])

In [101]:
for tag in tag2idx.keys():
    print(f'tag:{tag}')    
    print('\t TN:{:10}\tFP:{:10}'.format(TN[tag],FP[tag]))
    print('\t FN:{:10}\tTP:{:10}'.format(FN[tag],TP[tag]))  

tag:O
	 TN:         0	FP:         0
	 FN:         0	TP:    696169
tag:CONTENT
	 TN:         0	FP:         0
	 FN:     56040	TP:         0
tag:SOURCE
	 TN:         0	FP:         0
	 FN:      9511	TP:         0
tag:CUE
	 TN:         0	FP:         0
	 FN:      5038	TP:         0
