# Notebook
https://www.kaggle.com/williamroe/bi-lstm-with-crf-for-ner

In [ ]:
# %pip install tensorflow==2.4.0  # 2.5.0  # 2.2.0
%pip install tensorflow==2.5.0 

In [ ]:
# %pip install tensorflow_addons==0.13.0

In [ ]:
# %pip install keras-crf==0.2.0

In [ ]:
%pip install tensorflow-cpu==2.5.0

In [ ]:
# %pip install git+https://www.github.com/keras-team/keras-contrib.git
# # %pip install keras-contrib==0.1

In [ ]:
# https://github.com/xuxingya/tf2crf
# %pip install tf2crf==0.1.32

In [ ]:
# %env SM_FRAMEWORK=tf.keras

In [ ]:
# %pip uninstall --yes tf-nightly

In [ ]:
%pip install s3fs

In [1]:
import numpy as np
import pandas as pd 
# import s3fs

what_corpus = 'polnear'
what_type_files = 'train'
what_type_test_file = 'test'
what_type_val_file = 'dev'

# filepath = 's3://sagemaker-studio-528576943967-ssf9zkrg3os/polnear-conll/prepared/'
filepath = '../' + what_corpus + '-conll/prepared/'

In [2]:
train_filename = what_corpus + '_preprocessed_' + what_type_files + '_noBIO.csv'
df_train = pd.read_csv(filepath + train_filename, sep=";")

In [3]:
df_train[df_train['tag'].isna()]

Empty DataFrame
Columns: [Unnamed: 0, filename, sentence_idx, word, tag]
Index: []

In [4]:
print(len(df_train.index))
del df_train['Unnamed: 0']
df_train.head(20)

727161


filename  sentence_idx  \
0   politico_2016-05-22_mark-cuban-i-d-consider-a-...             1   
1   politico_2016-05-22_mark-cuban-i-d-consider-a-...             1   
2   politico_2016-05-22_mark-cuban-i-d-consider-a-...             1   
3   politico_2016-05-22_mark-cuban-i-d-consider-a-...             1   
4   politico_2016-05-22_mark-cuban-i-d-consider-a-...             1   
5   politico_2016-05-22_mark-cuban-i-d-consider-a-...             1   
6   politico_2016-05-22_mark-cuban-i-d-consider-a-...             1   
7   politico_2016-05-22_mark-cuban-i-d-consider-a-...             1   
8   politico_2016-05-22_mark-cuban-i-d-consider-a-...             1   
9   politico_2016-05-22_mark-cuban-i-d-consider-a-...             1   
10  politico_2016-05-22_mark-cuban-i-d-consider-a-...             1   
11  politico_2016-05-22_mark-cuban-i-d-consider-a-...             1   
12  politico_2016-05-22_mark-cuban-i-d-consider-a-...             2   
13  politico_2016-05-22_mark-cuban-i-d-consider-a-...             2   
14  politico_2016-05-22_mark-cuban-i-d-consider-a-...             2   
15  politico_2016-05-22_mark-cuban-i-d-consider-a-...             2   
16  politico_2016-05-22_mark-cuban-i-d-consider-a-...             2   
17  politico_2016-05-22_mark-cuban-i-d-consider-a-...             2   
18  politico_2016-05-22_mark-cuban-i-d-consider-a-...             2   
19  politico_2016-05-22_mark-cuban-i-d-consider-a-...             2   

           word      tag  
0          Mark   SOURCE  
1         Cuban   SOURCE  
2             :      CUE  
3             I  CONTENT  
4         would  CONTENT  
5      consider  CONTENT  
6             a  CONTENT  
7        future  CONTENT  
8         White  CONTENT  
9         House  CONTENT  
10          bid  CONTENT  
11            .        O  
12         Mark   SOURCE  
13        Cuban   SOURCE  
14            ,   SOURCE  
15          the   SOURCE  
16  billionaire   SOURCE  
17        owner   SOURCE  
18           of   SOURCE  
19          the   SOURCE

In [5]:
test_filename = what_corpus + '_preprocessed_' + what_type_test_file + '_noBIO.csv'
df_test = pd.read_csv(filepath + test_filename, sep=";")

In [6]:
print(len(df_test.index))
del df_test['Unnamed: 0']
df_test.head(20)

73370


filename  sentence_idx  \
0   huff-post_2016-11-05_hillary-clinton-drops-int...             1   
1   huff-post_2016-11-05_hillary-clinton-drops-int...             1   
2   huff-post_2016-11-05_hillary-clinton-drops-int...             1   
3   huff-post_2016-11-05_hillary-clinton-drops-int...             1   
4   huff-post_2016-11-05_hillary-clinton-drops-int...             1   
5   huff-post_2016-11-05_hillary-clinton-drops-int...             1   
6   huff-post_2016-11-05_hillary-clinton-drops-int...             1   
7   huff-post_2016-11-05_hillary-clinton-drops-int...             1   
8   huff-post_2016-11-05_hillary-clinton-drops-int...             1   
9   huff-post_2016-11-05_hillary-clinton-drops-int...             1   
10  huff-post_2016-11-05_hillary-clinton-drops-int...             1   
11  huff-post_2016-11-05_hillary-clinton-drops-int...             1   
12  huff-post_2016-11-05_hillary-clinton-drops-int...             1   
13  huff-post_2016-11-05_hillary-clinton-drops-int...             2   
14  huff-post_2016-11-05_hillary-clinton-drops-int...             2   
15  huff-post_2016-11-05_hillary-clinton-drops-int...             2   
16  huff-post_2016-11-05_hillary-clinton-drops-int...             2   
17  huff-post_2016-11-05_hillary-clinton-drops-int...             2   
18  huff-post_2016-11-05_hillary-clinton-drops-int...             2   
19  huff-post_2016-11-05_hillary-clinton-drops-int...             2   

            word      tag  
0        Hillary        O  
1        Clinton        O  
2          drops        O  
3           Into        O  
4        Detroit        O  
5             as        O  
6      Democrats   SOURCE  
7            get      CUE  
8        nervous      CUE  
9          about      CUE  
10         black  CONTENT  
11       turnout  CONTENT  
12             .        O  
13       DETROIT        O  
14            --        O  
15          with        O  
16     Democrats   SOURCE  
17  increasingly      CUE  
18       nervous      CUE  
19         about      CUE

In [7]:
df_test[df_test['tag'].isna()]

Empty DataFrame
Columns: [filename, sentence_idx, word, tag]
Index: []

In [8]:
val_filename = what_corpus + '_preprocessed_' + what_type_val_file + '_noBIO.csv'
df_val = pd.read_csv(filepath + val_filename, sep=";")

In [9]:
print(len(df_val.index))
del df_val['Unnamed: 0']
df_val.head(20)

78348


filename  sentence_idx  \
0   west-journal_2016-09-29_gold-star-mom-corners-...             1   
1   west-journal_2016-09-29_gold-star-mom-corners-...             1   
2   west-journal_2016-09-29_gold-star-mom-corners-...             1   
3   west-journal_2016-09-29_gold-star-mom-corners-...             1   
4   west-journal_2016-09-29_gold-star-mom-corners-...             1   
5   west-journal_2016-09-29_gold-star-mom-corners-...             1   
6   west-journal_2016-09-29_gold-star-mom-corners-...             1   
7   west-journal_2016-09-29_gold-star-mom-corners-...             1   
8   west-journal_2016-09-29_gold-star-mom-corners-...             1   
9   west-journal_2016-09-29_gold-star-mom-corners-...             1   
10  west-journal_2016-09-29_gold-star-mom-corners-...             1   
11  west-journal_2016-09-29_gold-star-mom-corners-...             1   
12  west-journal_2016-09-29_gold-star-mom-corners-...             1   
13  west-journal_2016-09-29_gold-star-mom-corners-...             1   
14  west-journal_2016-09-29_gold-star-mom-corners-...             1   
15  west-journal_2016-09-29_gold-star-mom-corners-...             1   
16  west-journal_2016-09-29_gold-star-mom-corners-...             1   
17  west-journal_2016-09-29_gold-star-mom-corners-...             2   
18  west-journal_2016-09-29_gold-star-mom-corners-...             2   
19  west-journal_2016-09-29_gold-star-mom-corners-...             2   

         word      tag  
0        Gold        O  
1        Star        O  
2         mom        O  
3     Corners        O  
4       Obama        O  
5          on        O  
6          he   SOURCE  
7     refusal      CUE  
8          to  CONTENT  
9         use  CONTENT  
10        the  CONTENT  
11       word  CONTENT  
12          `  CONTENT  
13    islamic  CONTENT  
14  terrorist  CONTENT  
15          .  CONTENT  
16          '  CONTENT  
17  President   SOURCE  
18     Barack   SOURCE  
19      Obama   SOURCE

In [10]:
df_val[df_val['tag'].isna()]

Empty DataFrame
Columns: [filename, sentence_idx, word, tag]
Index: []

In [11]:
class SentenceGetter(object):
    
    def __init__(self, dataset):
        self.n_sent = 1
        self.dataset = dataset
        self.empty = False
#         agg_func = lambda s: ' '.join(s["word"].values.tolist())
        agg_func = lambda s: [(w, t) for w,t in zip(s["word"].values.tolist(),
                                                        s["tag"].values.tolist())]
        self.grouped = self.dataset.groupby(["filename", "sentence_idx"]).apply(agg_func)
#         self.grouped = self.dataset.groupby(["sentence_idx"]).apply(agg_func)
        self.sentences = [s for s in self.grouped]
    
    def get_next(self):
        try:
            s = self.grouped["Sentence: {}".format(self.n_sent)]
            self.n_sent += 1
            return s
        except:
            return None

In [12]:
getter_train = SentenceGetter(df_train)
getter_test = SentenceGetter(df_test)
getter_val = SentenceGetter(df_val)

In [13]:
sentences_train = getter_train.sentences
sentences_test = getter_test.sentences
sentences_val = getter_val.sentences

In [14]:
print(len(sentences_train))
print(len(sentences_train)/2)

30343
15171.5


In [15]:
# sentences_train = sentences_train[0:15171]  # parc: 22352]
# print(len(sentences_train))

In [16]:
print(sentences_train[1])

[('in', 'O'), ('we', 'O'), ('last', 'O'), ('epistle', 'O'), ('from', 'O'), ('the', 'O'), ('bottomless', 'O'), ('pit', 'O'), (',', 'O'), ('we', 'SOURCE'), ('mock', 'CUE'), ('the', 'CONTENT'), ('presidential', 'CONTENT'), ('ambition', 'CONTENT'), ('of', 'CONTENT'), ('three', 'CONTENT'), ('republican', 'CONTENT'), ('hopeful', 'CONTENT'), (':', 'CONTENT'), ('Jeb', 'CONTENT'), ('!', 'CONTENT')]


In [17]:
# print(sentences_train[10])

In [18]:
print(len(sentences_test))

3022


In [19]:
# print(sentences_test[10])

In [20]:
maxlen = max([len(s) for s in sentences_train])
print ('Maximum sequence length train:', maxlen)
maxlen_test = max([len(s) for s in sentences_test])
print ('Maximum sequence length test:', maxlen_test)
maxlen_val = max([len(s) for s in sentences_val])
print ('Maximum sequence length val:', maxlen_val)

Maximum sequence length train: 220
Maximum sequence length test: 94
Maximum sequence length val: 95


In [21]:
# words_train = ['', '[UNK]']
# words_train.extend(list(set(df_train["word"].values)))
# words_train.append("ENDPAD")
# words_train[0:5]

In [22]:
sentences_texts_train = [' '.join([w[0] for w in s]) for s in sentences_train]
sentences_texts_train[1]

'in we last epistle from the bottomless pit , we mock the presidential ambition of three republican hopeful : Jeb !'

In [23]:
sentences_texts_test = [' '.join([w[0] for w in s]) for s in sentences_test]
sentences_texts_test[1]

'Washington -lrb- AFP -rrb- -- the Washington Post on Thursday become the latest US newspaper to emphatically endorse Hillary Clinton for the White House , say it be sway as much by she competence as by the alarming specter of a Donald Trump presidency .'

In [24]:
sentences_texts_val = [' '.join([w[0] for w in s]) for s in sentences_val]
sentences_texts_val[1]

"the New York Post report that Hillary Clinton 's team avoid take she to the emergency room follow she medical scare on Sunday in order to `` keep the detail of she medical treatment under wrap . ''"

https://keras.io/examples/nlp/pretrained_word_embeddings/


In [25]:
from tensorflow.data import Dataset
from tensorflow.keras.layers.experimental.preprocessing import TextVectorization

vectorizer = TextVectorization(max_tokens=50000, output_sequence_length=maxlen)
# vectorizer = TextVectorization(max_tokens=20000, output_sequence_length=200)
# text_ds = Dataset.from_tensor_slices(df_train["word"].values).batch(128)
text_ds = Dataset.from_tensor_slices(sentences_texts_train).batch(128)
vectorizer.adapt(text_ds)

In [26]:
vectorizer.get_vocabulary()[:5]

['', '[UNK]', 'the', 'be', 'to']

In [27]:
# output = vectorizer([["the cat sat on the mat"]])
# output.numpy()[0, :6]

In [28]:
voc = vectorizer.get_vocabulary()
word_index = dict(zip(voc, range(len(voc))))

In [29]:
test = ["the", "be", "get", "on", "the"]
[word_index[w] for w in test]

[2, 3, 71, 15, 2]

In [30]:
from gensim.models import KeyedVectors
# word_vecs = KeyedVectors.load_word2vec_format("glove.txt") 
# https://www.kaggle.com/watts2/glove6b50dtxt
glove_dimensions = 50
!python -m gensim.scripts.glove2word2vec --input  glove.6B.50d.txt --output glove.6B.50d.w2vformat.txt
word_vecs = KeyedVectors.load_word2vec_format("glove.6B.50d.w2vformat.txt")

/Users/bettyvandongen/opt/anaconda3/lib/python3.8/runpy.py:127: RuntimeWarning: 'gensim.scripts.glove2word2vec' found in sys.modules after import of package 'gensim.scripts', but prior to execution of 'gensim.scripts.glove2word2vec'; this may result in unpredictable behaviour
  warn(RuntimeWarning(msg))
2021-06-16 23:03:03,695 - glove2word2vec - INFO - running /Users/bettyvandongen/opt/anaconda3/lib/python3.8/site-packages/gensim/scripts/glove2word2vec.py --input glove.6B.50d.txt --output glove.6B.50d.w2vformat.txt
2021-06-16 23:03:03,835 - glove2word2vec - INFO - converting 400000 vectors from glove.6B.50d.txt to glove.6B.50d.w2vformat.txt
2021-06-16 23:03:04,251 - glove2word2vec - INFO - Converted model with 400000 vectors and 50 dimensions


In [31]:
# Test word_vecs
word_vecs.word_vec('the')

array([ 4.1800e-01,  2.4968e-01, -4.1242e-01,  1.2170e-01,  3.4527e-01,
       -4.4457e-02, -4.9688e-01, -1.7862e-01, -6.6023e-04, -6.5660e-01,
        2.7843e-01, -1.4767e-01, -5.5677e-01,  1.4658e-01, -9.5095e-03,
        1.1658e-02,  1.0204e-01, -1.2792e-01, -8.4430e-01, -1.2181e-01,
       -1.6801e-02, -3.3279e-01, -1.5520e-01, -2.3131e-01, -1.9181e-01,
       -1.8823e+00, -7.6746e-01,  9.9051e-02, -4.2125e-01, -1.9526e-01,
        4.0071e+00, -1.8594e-01, -5.2287e-01, -3.1681e-01,  5.9213e-04,
        7.4449e-03,  1.7778e-01, -1.5897e-01,  1.2041e-02, -5.4223e-02,
       -2.9871e-01, -1.5749e-01, -3.4758e-01, -4.5637e-02, -4.4251e-01,
        1.8785e-01,  2.7849e-03, -1.8411e-01, -1.1514e-01, -7.8581e-01],
      dtype=float32)

In [32]:
# np.array(word_vecs.word_vec('the')).astype(np.float16)

In [33]:
num_tokens = len(voc) + 2
embedding_dim = glove_dimensions
hits = 0
misses = 0

# Prepare embedding matrix
embedding_matrix = np.zeros((num_tokens, embedding_dim))
for word, i in word_index.items():
# for i, word in enumerate(words_train):
#     embedding_vector = embeddings_index.get(word)
#     print(i)
    try:
        embedding_vector = word_vecs.word_vec(word)
#     if embedding_vector is not None:
        # Words not found in embedding index will be all-zeros.
        # This includes the representation for "padding" and "OOV"
        embedding_matrix[i] = embedding_vector
        hits += 1
#     else:
    except KeyError:
        misses += 1
print("Converted %d words (%d misses)" % (hits, misses))

Converted 18285 words (3714 misses)


In [34]:
# words_test = list(set(df_test["word"].values))
# words_test.append("ENDPAD")

In [35]:
# n_words = len(words_train)
# n_words

In [36]:
# df_train[df_train['tag'].isna()]

In [37]:
from math import nan

tags = []
for index, tag in enumerate(set(df_train["tag"].values)):
    if tag is nan or isinstance(tag, float):
        tags.append('unk')
    else:
        tags.append(tag)
print(tags)

['CUE', 'SOURCE', 'O', 'CONTENT']


In [38]:
n_tags = len(tags); n_tags

4

In [39]:
from future.utils import iteritems
# word2idx_train = {w: i for i, w in enumerate(words_train)}
# word2idx_test = {w: i for i, w in enumerate(words_test)}

tag2idx = {t: i for i, t in enumerate(tags)}
idx2tag = {v: k for k, v in iteritems(tag2idx)}

In [40]:
# word2idx_train['the']

In [41]:
# word2idx

In [42]:
tag2idx["O"]

2

In [43]:
print(tag2idx)

{'CUE': 0, 'SOURCE': 1, 'O': 2, 'CONTENT': 3}


In [44]:
idx2tag[3]

'CONTENT'

In [45]:
idx2tag

{0: 'CUE', 1: 'SOURCE', 2: 'O', 3: 'CONTENT'}

In [46]:
X_train = vectorizer(np.array([[s] for s in sentences_texts_train])).numpy()
X_test = vectorizer(np.array([[s] for s in sentences_texts_test])).numpy()
X_val = vectorizer(np.array([[s] for s in sentences_texts_val])).numpy()

In [47]:
from tensorflow.keras.preprocessing.sequence import pad_sequences

In [48]:
# X_train = [[word2idx_train[w[0]] for w in s] for s in sentences_train]
# X_test = [[word2idx_test[w[0]] for w in s] for s in sentences_test]

In [49]:
print(X_train[10])

[ 1055     9   755    10    71     5   406 18235  7390    15   439   227
   451     3     5  5392  3335    14     9    37 18916     7    86   101
     9    70  4031     0     0     0     0     0     0     0     0     0
     0     0     0     0     0     0     0     0     0     0     0     0
     0     0     0     0     0     0     0     0     0     0     0     0
     0     0     0     0     0     0     0     0     0     0     0     0
     0     0     0     0     0     0     0     0     0     0     0     0
     0     0     0     0     0     0     0     0     0     0     0     0
     0     0     0     0     0     0     0     0     0     0     0     0
     0     0     0     0     0     0     0     0     0     0     0     0
     0     0     0     0     0     0     0     0     0     0     0     0
     0     0     0     0     0     0     0     0     0     0     0     0
     0     0     0     0     0     0     0     0     0     0     0     0
     0     0     0     0     0     0     0     0   

In [50]:
np.array(X_train).shape

(30343, 220)

In [51]:
# X_train = pad_sequences(maxlen=maxlen, sequences=X_train, padding="post",value=n_words - 1)
# print(X_train[10])

In [52]:
# X_test = pad_sequences(maxlen=maxlen, sequences=X_test, padding="post",value=n_words - 1)
# print(X_test[10])

In [53]:
y_idx_train = [[tag2idx[w[1]] for w in s] for s in sentences_train]
# print('sentences_train[25]')
# print(sentences_train[25])
# print('y_idx_train[25]')
# print(y_idx_train[25])
# print('sentences_train[10]')
# print(sentences_train[10])
# print('y_idx_train[10]')
# print(y_idx_train[10])
# print(len(y_idx_train[10]))

In [54]:
y_idx_test = [[tag2idx[w[1]] for w in s] for s in sentences_test]
# print('sentences_test[25]')
# print(sentences_test[25])
# print('y_idx_test[25]')
# print(y_idx_test[25])
# print('sentences_test[10]')
# print(sentences_test[10])
# print('y_idx_test[10]')
# print(y_idx_test[10])
# print(len(y_idx_test[10]))

In [55]:
y_idx_val = [[tag2idx[w[1]] for w in s] for s in sentences_val]

In [56]:
y_train = pad_sequences(maxlen=maxlen, sequences=y_idx_train, padding="post", value=tag2idx["O"])
print(y_train[10])
print(len(y_train[10]))

[2 1 0 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 2 2 2 2 2 2 2 2
 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2
 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2
 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2
 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2
 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2]
220


In [57]:
y_test = pad_sequences(maxlen=maxlen, sequences=y_idx_test, padding="post", value=tag2idx["O"])
print(y_test[10])
print(len(y_test[10]))

[1 1 1 0 0 0 0 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 2 2 2 2 2 2 2 2 2 2 2 2
 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2
 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2
 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2
 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2
 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2]
220


In [58]:
y_val = pad_sequences(maxlen=maxlen, sequences=y_idx_val, padding="post", value=tag2idx["O"])
print(y_val[10])
print(len(y_val[10]))

[3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 0 1 2 2 2 2 2 2
 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2
 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2
 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2
 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2
 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2]
220


In [59]:
from tensorflow.keras.utils import to_categorical
y_train = [to_categorical(i, num_classes=n_tags) for i in y_train]
print(y_train[10][0])

[0. 0. 1. 0.]


In [60]:
y_test = [to_categorical(i, num_classes=n_tags) for i in y_test]
print(y_test[10][0])

[0. 1. 0. 0.]


In [61]:
y_val = [to_categorical(i, num_classes=n_tags) for i in y_val]
print(y_val[10][0])

[0. 0. 0. 1.]


In [62]:
# from sklearn.model_selection import train_test_split
# X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.5)

# X_train, y_train = X, y
# X_test, y_test = X, y

In [63]:
print(X_train[10][0])
print(X_test[10][0])
print(X_val[10][0])
print(y_train[10][0])
print(y_test[10][0])
print(y_val[10][0])

1055
2
47
[0. 0. 1. 0.]
[0. 1. 0. 0.]
[0. 0. 0. 1.]


In [64]:
from tensorflow.keras.initializers import Constant
from tensorflow.keras.layers import Input, InputLayer, LSTM, Embedding, Dense, TimeDistributed, Dropout, Bidirectional
from tensorflow.keras.models import Model, Sequential  # , Input
import tensorflow.keras as k
import tensorflow as tf

In [65]:
print(k.__version__)

2.5.0


In [66]:
# import tensorflow.keras.utils as generic_utils
# from keras_contrib.layers.crf import CRF
# AttributeError: module 'tensorflow.compat.v2' has no attribute '__internal__'

In [67]:
word_embedding_size = embedding_dim  # glove_dimensions  # 300

https://github.com/xuxingya/tf2crf

More inspiration:
https://github.com/Akshayc1/named-entity-recognition/blob/master/NER%20using%20Bidirectional%20LSTM%20-%20CRF%20.ipynb
https://www.kaggle.com/nikkisharma536/ner-with-bilstm-and-crf

In [68]:
# # Kaggle example code 

# inputs = Input(shape=(None,), dtype="int64")  
# # inputs = Input(shape=(maxlen,))
# # https://stackoverflow.com/questions/55770009/how-to-use-a-pre-trained-embedding-matrix-in-tensorflow-2-0-rnn-as-initial-weigh
# # https://keras.io/examples/nlp/pretrained_word_embeddings/ --> pretrained embeddings
# # outputs = Embedding(input_dim=n_words, output_dim=word_embedding_size, input_length=maxlen)(inputs)
# outputs = Embedding(num_tokens, embedding_dim, embeddings_initializer=Constant(embedding_matrix), trainable=False,)(inputs)
# outputs = Bidirectional(LSTM(units=word_embedding_size, 
#                              return_sequences=True, 
#                              dropout=0.5,  # 0.2, 0.5, 
#                              recurrent_dropout=0.5,  # 0.2, 0.5, 
#                              kernel_initializer=k.initializers.he_normal()))(outputs)
# # https://github.com/xuxingya/tf2crf: Add internal kernel like CRF in keras_contrib, so now there is no need to stack a Dense layer before the CRF layer.
# # outputs = Dense(n_tags, activation="relu")(outputs)  # previously softmax output layer
# outputs = TimeDistributed(Dense(n_tags, activation="relu"))(outputs)  # previously softmax output layer
# # outputs = TimeDistributed(Dense(n_tags, activation=tensorflow.keras.activations.softmax))(outputs)  # previously softmax output layer

# # crf = CRF(n_tags)  # CRF layer
# # out = crf(outputs)  # output
# # model = Model(input, out)

# # adam = k.optimizers.Adam(lr=0.0005, beta_1=0.9, beta_2=0.999)
# adam = k.optimizers.Adam(learning_rate=0.0005, beta_1=0.9, beta_2=0.999)

# model = Model(inputs, outputs)

# # https://stackoverflow.com/questions/61742556/valueerror-shapes-none-1-and-none-2-are-incompatible
# # model.compile(optimizer='adam', loss="sparse_categorical_crossentropy", metrics=["accuracy"])
# model.compile(optimizer=adam, loss="categorical_crossentropy", metrics=["accuracy"])  # categorical_accuracy?
# # model.compile(loss="sparse_categorical_crossentropy", optimizer="rmsprop", metrics=["acc"])
# # model.compile(optimizer=adam, loss=crf.loss_function, metrics=[crf.accuracy, 'accuracy'])# Saving the best only

# model.summary()

In [69]:
# https://github.com/tensorflow/addons/issues/1769
from crf import CRF

model = Sequential()
model.add(InputLayer(input_shape=(None,), dtype="int64"))
model.add(Embedding(num_tokens, embedding_dim, embeddings_initializer=Constant(embedding_matrix), trainable=False,))
model.add(Bidirectional(LSTM(units=word_embedding_size, 
                             return_sequences=True, 
                             dropout=0.5,  # 0.2, 0.5, 
                             recurrent_dropout=0.5,  # 0.2, 0.5, 
                             kernel_initializer=k.initializers.he_normal())))
model.add(TimeDistributed(Dense(n_tags, activation="relu")))

adam = k.optimizers.Adam(learning_rate=0.0005, beta_1=0.9, beta_2=0.999)

crf = CRF(n_tags, sparse_target=False)
model.add(crf)
model.compile(optimizer=adam, loss="categorical_crossentropy", metrics=["accuracy"])  # categorical_accuracy?
# model.compile(optimizer=adam, loss=crf.loss, metrics=[crf.accuracy])
model.summary()

# /Users/bettyvandongen/opt/anaconda3/lib/python3.8/site-packages/tensorflow_addons/text/crf.py:540: 
# UserWarning: CRF Decoding does not work with KerasTensors in TF2.4. The bug has since been fixed in tensorflow/tensorflow##45534

/Users/bettyvandongen/opt/anaconda3/lib/python3.8/site-packages/tensorflow/python/autograph/impl/api.py:376: UserWarning: CRF decoding models have serialization issues in TF >=2.5 . Please see isse #2476
  return py_builtins.overload_of(f)(*args)


Model: "sequential"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
embedding (Embedding)        (None, None, 50)          1100050   
_________________________________________________________________
bidirectional (Bidirectional (None, None, 100)         40400     
_________________________________________________________________
time_distributed (TimeDistri (None, None, 4)           404       
_________________________________________________________________
crf (CRF)                    (None, None, 4)           16        
Total params: 1,140,870
Trainable params: 40,820
Non-trainable params: 1,100,050
_________________________________________________________________


In [70]:
# # Saving the best only
from tensorflow.keras.callbacks import ModelCheckpoint

# filepath="ner-bi-lstm-td-model-{val_accuracy:.2f}.hdf5"
filepath = 'tmp/checkpoint'
checkpoint_acc = ModelCheckpoint(filepath + '/acc', monitor='val_accuracy', verbose=1, save_best_only=True, mode='max')
checkpoint_loss = ModelCheckpoint(filepath + '/loss', monitor='val_loss', verbose=1, save_best_only=True, mode='max')
callbacks_list = [checkpoint_acc, checkpoint_loss]

In [71]:
# # Generate generalization metrics
# i = len(X_test) - 1 
# score = model.evaluate(np.array([X_test[:i]]), y_test, verbose=0)
# print(f'Test loss: {score[0]} / Test accuracy: {score[1]}')

In [72]:
# model.fit(X_train, np.array(y_train), batch_size=256, epochs=1, validation_split=0.1, verbose=1, callbacks=callbacks_list)
model.fit(X_train, np.array(y_train), batch_size=256, epochs=1, validation_split=0.2, verbose=1, callbacks=callbacks_list)
# model.fit(X_train, np.array(y_train), batch_size=256, epochs=50, validation_data=(X_val, y_val), verbose=1, callbacks=callbacks_list)

95/95 [==============================] - 54s 535ms/step - loss: nan - accuracy: 0.0072 - val_loss: 16.0239 - val_accuracy: 0.0058

Epoch 00001: val_accuracy improved from -inf to 0.00585, saving model to tmp/checkpoint/acc


/Users/bettyvandongen/opt/anaconda3/lib/python3.8/site-packages/tensorflow_addons/text/crf.py:545: UserWarning: CRF decoding models have serialization issues in TF >=2.5 . Please see isse #2476
  warnings.warn(
/Users/bettyvandongen/opt/anaconda3/lib/python3.8/site-packages/tensorflow/python/autograph/impl/api.py:376: UserWarning: CRF decoding models have serialization issues in TF >=2.5 . Please see isse #2476
  return py_builtins.overload_of(f)(*args)
/Users/bettyvandongen/opt/anaconda3/lib/python3.8/site-packages/tensorflow_addons/text/crf.py:545: UserWarning: CRF decoding models have serialization issues in TF >=2.5 . Please see isse #2476
  warnings.warn(


INFO:tensorflow:Assets written to: tmp/checkpoint/acc/assets

Epoch 00001: val_loss improved from -inf to 16.02386, saving model to tmp/checkpoint/loss


/Users/bettyvandongen/opt/anaconda3/lib/python3.8/site-packages/tensorflow/python/autograph/impl/api.py:376: UserWarning: CRF decoding models have serialization issues in TF >=2.5 . Please see isse #2476
  return py_builtins.overload_of(f)(*args)
/Users/bettyvandongen/opt/anaconda3/lib/python3.8/site-packages/tensorflow_addons/text/crf.py:545: UserWarning: CRF decoding models have serialization issues in TF >=2.5 . Please see isse #2476
  warnings.warn(
/Users/bettyvandongen/opt/anaconda3/lib/python3.8/site-packages/tensorflow/python/autograph/impl/api.py:376: UserWarning: CRF decoding models have serialization issues in TF >=2.5 . Please see isse #2476
  return py_builtins.overload_of(f)(*args)
/Users/bettyvandongen/opt/anaconda3/lib/python3.8/site-packages/tensorflow_addons/text/crf.py:545: UserWarning: CRF decoding models have serialization issues in TF >=2.5 . Please see isse #2476
  warnings.warn(


INFO:tensorflow:Assets written to: tmp/checkpoint/loss/assets


In [73]:
model.summary()

Model: "sequential"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
embedding (Embedding)        (None, None, 50)          1100050   
_________________________________________________________________
bidirectional (Bidirectional (None, None, 100)         40400     
_________________________________________________________________
time_distributed (TimeDistri (None, None, 4)           404       
_________________________________________________________________
crf (CRF)                    (None, None, 4)           16        
Total params: 1,140,870
Trainable params: 40,820
Non-trainable params: 1,100,050
_________________________________________________________________


In [74]:
TP = {}
TN = {}
FP = {}
FN = {}
for tag in tag2idx.keys():
    TP[tag] = 0
    TN[tag] = 0    
    FP[tag] = 0    
    FN[tag] = 0    

def accumulate_score_by_tag(gt, pred):
    """
    For each tag keep stats
    """
    if gt == pred:
        TP[gt] += 1
    elif gt != 'O' and pred == 'O':
        FN[gt] +=1
    elif gt == 'O' and pred != 'O':
        FP[gt] += 1
    else:
        TN[gt] += 1

In [75]:
print(X_test)

[[ 195  264  132 ...    0    0    0]
 [ 195   84 3831 ...    0    0    0]
 [  67   21   11 ...    0    0    0]
 ...
 [  20    3  848 ...    0    0    0]
 [  27   36  212 ...    0    0    0]
 [   7   24  177 ...    0    0    0]]


In [76]:
### Predict single sentence

In [77]:
# i = 2  # len(X_test) - 1  # Last one 
# p = model.predict(np.array([X_test[i]]))
# p = np.argmax(p, axis=-1)
# print(p.shape)
# gt = np.argmax(y_test[i], axis=-1)
# print(gt)
# print("{:14}: ({:5}): {}".format("Word", "True", "Pred"))
# print(p)
# for idx, (w,pred) in enumerate(zip(X_test[i],p[0])):
#     if words_test[w] == 'ENDPAD':
#         break
#     print("{:14}: ({:5}): {}".format(words_test[w],idx2tag[gt[idx]],tags[pred]))

In [ ]:
p = model.predict(np.array(X_test))

/Users/bettyvandongen/opt/anaconda3/lib/python3.8/site-packages/tensorflow/python/autograph/impl/api.py:376: UserWarning: CRF decoding models have serialization issues in TF >=2.5 . Please see isse #2476
  return py_builtins.overload_of(f)(*args)


In [ ]:
p.shape

In [ ]:
p[0][0]

In [ ]:
p[100][100]

In [ ]:
# p

In [ ]:
from sklearn.metrics import classification_report

In [ ]:
axis = 2

In [ ]:
np.argmax(p, axis=axis)[0]

In [ ]:
print(classification_report(np.argmax(y_test, axis=axis).ravel(), np.argmax(p, axis=axis).ravel(),labels=list(idx2tag.keys()), target_names=list(idx2tag.values())))

In [ ]:
for i, sentence in enumerate(X_test):
    y_hat = np.argmax(p[i], axis=-1)
    gt = np.argmax(y_test[i], axis=-1)
    for idx, (w,pred) in enumerate(zip(sentence,y_hat)):
        accumulate_score_by_tag(idx2tag[gt[idx]],tags[pred])

In [ ]:
for tag in tag2idx.keys():
    print(f'tag:{tag}')    
    print('\t TN:{:10}\tFP:{:10}'.format(TN[tag],FP[tag]))
    print('\t FN:{:10}\tTP:{:10}'.format(FN[tag],TP[tag]))  